baseURL = "https://example.org/"
title = "Nokull Demo"
theme = "nokull"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.ko]
    languageName = "한국어"
    languageCode = "ko-kr"
    weight = 1

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2

[params]
  description = "This is a demo"
